export const Users=[
    {
        id:1,
        profilePicture:"assets/person/1.jpeg",
        username:"Nila",
    },
    {
        id:2,
        profilePicture:"assets/person/2.jpeg",
        username:"Alex",
    },
    {
        id:3,
        profilePicture:"assets/person/3.jpeg",
        username:"Janell ",
    },
    {
        id:4,
        profilePicture:"assets/person/4.jpeg",
        username:"Analia",
    },
    {
        id:5,
        profilePicture:"assets/person/5.jpeg",
        username:"Peter",
    },
    {
        id:6,
        profilePicture:"assets/person/6.jpeg",
        username:"John",
    },
    {
        id:7,
        profilePicture:"assets/person/7.jpeg",
        username:"Kennedy",
    },
    {
        id:8,
        profilePicture:"assets/person/8.jpeg",
        username:"Paul",
    },
    {
        id:9,
        profilePicture:"assets/person/9.jpeg",
        username:"Kimberly",
    },
    {
        id:10,
        profilePicture:"assets/person/10.jpeg",
        username:"Watson",
    },
]

export const Posts=[
    {
    id:1,
    desc:"Love for All, Hatred For None",
    photo:"assets/post/1.jpg",
    date:"5 mins ago",
    userId:1,
    like:32,
    comment:8,
    },
    {
        id:2,
        desc:"Go ahead, make my day.",
        photo:"assets/post/2.jpg",
        date:"10 mins ago",
        userId:2,
        like:35,
        comment:9,
        },
        {
            id:3,
            desc:"Success is not final; failure is not fatal",
            photo:"assets/post/3.png",
            date:"5 mins ago",
            userId:3,
            like:37,
            comment:7,
            },
            {
                id:4,
                desc:"Spread love everywhere you go",
                photo:"assets/post/4.jpeg",
                date:"3 mins ago",
                userId:4,
                like:39,
                comment:6,
                },
                {
                    id:5,
                    desc:"Well done is better than well said",
                    photo:"assets/post/5.jpeg",
                    date:"4 mins ago",
                    userId:5,
                    like:38,
                    comment:5,
                    },
                    {
                        id:6,
                        desc:"“All dreams are within reach",
                        photo:"assets/post/6.jpg",
                        date:"8 mins ago",
                        userId:6,
                        like:38,
                        comment:5,
                        },
                        {
                            id:7,
                            desc:"The secret of getting ahead is getting started",
                            photo:"assets/post/7.jpeg",
                            date:"9 mins ago",
                            userId:7,
                            like:38,
                            comment:5,
                            },
                            {
                                id:8,
                                desc:"There is nothing impossible to they who will try",
                                photo:"assets/post/8.jpeg",
                                date:"6 mins ago",
                                userId:8,
                                like:38,
                                comment:5,
                                },
                                {
                                    id:9,
                                    desc:"Life has got all those twists and turns",
                                    photo:"assets/post/9.jpeg",
                                    date:"5 mins ago",
                                    userId:9,
                                    like:38,
                                    comment:5,
                                    },
]